// GENERATED by scripts/gen-types.mjs — do not edit by hand.
// Regenerate after every migration:  npm run db:types
//
// Hand-written domain types (ReplanOp, TripPrefs, and the narrowed unions used
// across the app) live in ./types.ts and import from here.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface AgentRunsRow {
  id: string;
  trip_id: string | null;
  kind: "intake" | "compose" | "replan" | "comms" | "copilot";
  status: "running" | "succeeded" | "failed";
  input: Json;
  output: Json | null;
  error: string | null;
  input_tokens: number | null;
  output_tokens: number | null;
  started_at: string;
  ended_at: string | null;
}

export type AgentRunsInsert = Omit<AgentRunsRow, "id" | "trip_id" | "status" | "input" | "output" | "error" | "input_tokens" | "output_tokens" | "started_at" | "ended_at"> & Partial<AgentRunsRow>;

export interface AgentStepsRow {
  id: string;
  run_id: string;
  seq: number;
  tool_name: string;
  tool_input: Json | null;
  tool_output: Json | null;
  ms: number | null;
  created_at: string;
}

export type AgentStepsInsert = Omit<AgentStepsRow, "id" | "tool_input" | "tool_output" | "ms" | "created_at"> & Partial<AgentStepsRow>;

export interface AvailabilityRow {
  id: string;
  inventory_id: string;
  date: string;
  starts_at: string;
  slots_total: number;
  slots_taken: number;
  price: number | null;
}

export type AvailabilityInsert = Omit<AvailabilityRow, "id" | "slots_total" | "slots_taken" | "price"> & Partial<AvailabilityRow>;

export interface BookingsRow {
  id: string;
  trip_id: string;
  item_id: string | null;
  vendor_id: string | null;
  state: "held" | "confirmed" | "cancelled" | "refunded" | "failed";
  amount: number;
  penalty: number;
  external_ref: string | null;
  created_at: string;
  updated_at: string;
}

export type BookingsInsert = Omit<BookingsRow, "id" | "item_id" | "vendor_id" | "state" | "amount" | "penalty" | "external_ref" | "created_at" | "updated_at"> & Partial<BookingsRow>;

export interface DisruptionsRow {
  id: string;
  trip_id: string;
  source: "weather" | "transport" | "vendor" | "manual";
  severity: "low" | "medium" | "high";
  headline: string;
  root_item_id: string | null;
  payload: Json;
  state: "open" | "resolved" | "dismissed";
  detected_at: string;
  resolved_at: string | null;
}

export type DisruptionsInsert = Omit<DisruptionsRow, "id" | "severity" | "root_item_id" | "payload" | "state" | "detected_at" | "resolved_at"> & Partial<DisruptionsRow>;

export interface InventoryRow {
  id: string;
  vendor_id: string;
  title: string;
  type: "hotel" | "activity" | "transport" | "guide" | "restaurant";
  description: string | null;
  duration_min: number;
  base_cost: number;
  lat: number | null;
  lng: number | null;
  opens_at: string | null;
  closes_at: string | null;
  tags: string[];
  weather_sensitive: boolean;
  created_at: string;
}

export type InventoryInsert = Omit<InventoryRow, "id" | "description" | "duration_min" | "base_cost" | "lat" | "lng" | "opens_at" | "closes_at" | "tags" | "weather_sensitive" | "created_at"> & Partial<InventoryRow>;

export interface ItineraryItemsRow {
  id: string;
  trip_id: string;
  day: number;
  seq: number;
  inventory_id: string | null;
  vendor_id: string | null;
  title: string;
  type: "hotel" | "activity" | "transport" | "guide" | "restaurant" | "flight";
  starts_at: string;
  ends_at: string;
  lat: number | null;
  lng: number | null;
  cost: number;
  status: "planned" | "confirmed" | "at_risk" | "cancelled" | "replaced";
  depends_on: string[];
  lock_reason: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
  field_state: "pending" | "on_track" | "done" | "issue";
  field_note: string | null;
  field_updated_at: string | null;
}

export type ItineraryItemsInsert = Omit<ItineraryItemsRow, "id" | "seq" | "inventory_id" | "vendor_id" | "lat" | "lng" | "cost" | "status" | "depends_on" | "lock_reason" | "notes" | "created_at" | "updated_at" | "field_state" | "field_note" | "field_updated_at"> & Partial<ItineraryItemsRow>;

export interface MessagesRow {
  id: string;
  trip_id: string | null;
  vendor_id: string | null;
  thread_key: string;
  direction: "outbound" | "inbound";
  from_role: "agent" | "operator" | "vendor" | "coordinator" | "traveler";
  body: string;
  structured: Json | null;
  sent_at: string;
}

export type MessagesInsert = Omit<MessagesRow, "id" | "trip_id" | "vendor_id" | "structured" | "sent_at"> & Partial<MessagesRow>;

export interface OperatorsRow {
  id: string;
  name: string;
  contact: string | null;
  created_at: string;
}

export type OperatorsInsert = Omit<OperatorsRow, "id" | "contact" | "created_at"> & Partial<OperatorsRow>;

export interface ProfilesRow {
  id: string;
  role: "traveler" | "operator" | "coordinator";
  full_name: string;
  email: string | null;
  phone: string | null;
  operator_id: string | null;
  created_at: string;
  updated_at: string;
}

export type ProfilesInsert = Omit<ProfilesRow, "role" | "full_name" | "email" | "phone" | "operator_id" | "created_at" | "updated_at"> & Partial<ProfilesRow>;

export interface ReplanProposalsRow {
  id: string;
  disruption_id: string;
  run_id: string | null;
  plan: Json;
  cost_delta: number;
  rationale: string | null;
  state: "draft" | "sent" | "accepted" | "rejected" | "superseded";
  created_at: string;
  decided_at: string | null;
  decided_by: string | null;
}

export type ReplanProposalsInsert = Omit<ReplanProposalsRow, "id" | "run_id" | "plan" | "cost_delta" | "rationale" | "state" | "created_at" | "decided_at" | "decided_by"> & Partial<ReplanProposalsRow>;

export interface TripsRow {
  id: string;
  traveler_id: string | null;
  operator_id: string | null;
  title: string;
  contact_name: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  status: "draft" | "quoted" | "confirmed" | "in_progress" | "completed" | "cancelled";
  party_size: number;
  budget: number | null;
  currency: string;
  starts_on: string | null;
  ends_on: string | null;
  prefs: Json;
  created_at: string;
  updated_at: string;
  coordinator_id: string | null;
  coordinator_name: string | null;
  coordinator_phone: string | null;
}

export type TripsInsert = Omit<TripsRow, "id" | "traveler_id" | "operator_id" | "title" | "contact_name" | "contact_email" | "contact_phone" | "status" | "party_size" | "budget" | "currency" | "starts_on" | "ends_on" | "prefs" | "created_at" | "updated_at" | "coordinator_id" | "coordinator_name" | "coordinator_phone"> & Partial<TripsRow>;

export interface VendorsRow {
  id: string;
  operator_id: string;
  name: string;
  type: "hotel" | "activity" | "transport" | "guide" | "restaurant";
  contact: string | null;
  email: string | null;
  phone: string | null;
  channel: "auto" | "manual";
  reliability: number;
  created_at: string;
}

export type VendorsInsert = Omit<VendorsRow, "id" | "contact" | "email" | "phone" | "channel" | "reliability" | "created_at"> & Partial<VendorsRow>;
