#!/usr/bin/env node
/**
 * Generate row types from the live schema — no Docker needed.
 *
 *   npm run db:types
 *
 * Note that the redirect truncates the target before this runs, so a failure
 * in here leaves an empty types file behind. Everything below therefore
 * connects and validates before printing a byte.
 *
 * `supabase gen types` needs a container runtime, and it renders text columns
 * with CHECK constraints as bare `string`. This reads information_schema
 * directly and turns those CHECKs into real string-literal unions, which is
 * where most of our domain vocabulary lives.
 */
import fs from "node:fs";
import pg from "pg";
import { loadEnv, connectionConfig, explain } from "./pg-config.mjs";

/**
 * Connects through `pg-config` like every other script here.
 *
 * It used to build its own client pinned to `db.<ref>.supabase.co`, which
 * publishes only an AAAA record — so on any network without an IPv6 route this
 * died with ETIMEDOUT while `db:push`, `db:seed` and `db:verify` all worked
 * fine through the pooler. Worse, the failure lands mid-pipeline: the shell has
 * already truncated `src/lib/db/generated.ts` by the time the connection gives
 * up, so a flaky network does not just fail to regenerate the types, it deletes
 * them and breaks the build.
 */
loadEnv();

const client = new pg.Client(connectionConfig());
try {
  await client.connect();
} catch (err) {
  console.error(`\nCould not connect to Postgres: ${explain(err)}`);
  process.exit(1);
}

const { rows: columns } = await client.query(`
  select table_name, column_name, data_type, udt_name, is_nullable,
         column_default is not null as has_default
    from information_schema.columns
   where table_schema = 'public'
   order by table_name, ordinal_position
`);

// Pull the allowed values out of simple `col = ANY (ARRAY['a','b'])` CHECKs.
const { rows: checks } = await client.query(`
  select rel.relname as table_name, pg_get_constraintdef(c.oid) as def
    from pg_constraint c
    join pg_class rel on rel.oid = c.conrelid
    join pg_namespace n on n.oid = rel.relnamespace
   where c.contype = 'c' and n.nspname = 'public'
`);

const unions = new Map(); // "table.column" -> ["a","b"]
for (const { table_name, def } of checks) {
  const col = def.match(/\(\(?([a-z_]+)\s*=\s*ANY/i)?.[1];
  const list = def.match(/ARRAY\[(.*?)\]/s)?.[1];
  if (!col || !list) continue;
  const values = [...list.matchAll(/'((?:[^']|'')*)'/g)].map((m) => m[1].replace(/''/g, "'"));
  if (values.length) unions.set(`${table_name}.${col}`, values);
}

/** node-postgres hands numerics back as strings, but app code reads through
 *  the Supabase client (PostgREST → JSON), where they arrive as numbers. */
function tsType(c) {
  if (c.data_type === "ARRAY") return c.udt_name === "_text" ? "string[]" : "string[]";
  switch (c.data_type) {
    case "boolean": return "boolean";
    case "integer": case "bigint": case "smallint":
    case "numeric": case "double precision": case "real": return "number";
    case "jsonb": case "json": return "Json";
    default: return "string";
  }
}

const byTable = new Map();
for (const c of columns) {
  if (!byTable.has(c.table_name)) byTable.set(c.table_name, []);
  byTable.get(c.table_name).push(c);
}

const pascal = (s) => s.replace(/(^|_)([a-z])/g, (_, __, ch) => ch.toUpperCase());

let out = `// GENERATED by scripts/gen-types.mjs — do not edit by hand.
// Regenerate after every migration:  npm run db:types
//
// Hand-written domain types (ReplanOp, TripPrefs, and the narrowed unions used
// across the app) live in ./types.ts and import from here.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];
`;

for (const [table, cols] of [...byTable].sort()) {
  out += `\nexport interface ${pascal(table)}Row {\n`;
  for (const c of cols) {
    const union = unions.get(`${table}.${c.column_name}`);
    const base = union ? union.map((v) => JSON.stringify(v)).join(" | ") : tsType(c);
    const nullable = c.is_nullable === "YES" ? " | null" : "";
    out += `  ${c.column_name}: ${base}${nullable};\n`;
  }
  out += `}\n`;
  // Insert shape: defaulted and nullable columns are optional.
  out += `\nexport type ${pascal(table)}Insert = Omit<${pascal(table)}Row, ${cols
    .filter((c) => c.has_default || c.is_nullable === "YES")
    .map((c) => JSON.stringify(c.column_name))
    .join(" | ") || "never"}> & Partial<${pascal(table)}Row>;\n`;
}

await client.end();
process.stdout.write(out);
